services:
  apigateway:
    build :
      context: .
      dockerfile: Dockerfile
    container_name: apigwy
    ports:
      - 8085:8085
    environment:
      server.port: 8085
      eureka.client.serviceUrl.defaultZone: http://servreg:8761/eureka
    networks:
      - foundit-network

networks:
  foundit-network:
    driver: bridge
