spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter

        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item/**
          filters:
            - AuthFilter

        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item/**
          filters:
            - AuthFilter

        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chats/**
          filters:
            - AuthFilter

        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/messages/**
          filters:
            - AuthFilter

  config:
    import: optional:file:.env[.properties]

  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://servreg:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

security:
  jwt:
    secret-key : f943ea3da5fcd77a7b78f184eaeac29d13fc20ef350edbbdb2e4c014172ee2c7e4bee4228047786ab3409b273eb048722e9227c774dd4f8fbd96ab7b438b9799

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8085