services:
  serviceregistry:
    image: tharukadk/service-registry:01
    container_name: servreg
    ports:
      - 8761:8761
    networks:
      - foundit-network

networks:
  foundit-network:
    driver: bridge
